# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

-   repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        stages: [commit]
        log_file: .black.log

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=pylintrc"]
        stages: [commit]
