[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "clipyx"
authors = [
  { name="G-Lauz", email="gabriel.lauzier@usherbrooke.ca" },
]
description = "Python package for creating command-line interfaces in a pythonic way."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/G-Lauz/clipy"
Issues = "https://github.com/G-Lauz/clipy/issues"

[tool.setuptools.dynamic]
version = {file = "VERSION"}

[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311', 'py312', 'py313']
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
)/
'''

[tool.isort]
profile = "black"
